package net.codeenergy.demo.DTO;
// Generated Mar 11, 2016 1:39:40 PM by Hibernate Tools 4.3.1.Final

/**
 * Product generated by hbm2java
 */

public class Product implements java.io.Serializable {

	private int id;
	private String name;
	private float price;
	private String description;

	public Product() {
	}

	public Product(int id, String name, float price, String description) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
